djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from djangoProject import settings
from dz6app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dz6app/', include('dz6app.urls', namespace='dz6app')),
    path('', views.my_page, name='my_page'),
    path('success/', views.save_success, name='save-success'),
    # path('__debug__/', include("debug_toolbar.urls")),
    path('template/', views.total_in_template, name='template'),
    path('subscribe/', views.subscribe, name='subscribe'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz6app/urls.py
from itertools import product

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings
from dz6app import views

app_name = 'dz6app'

urlpatterns = [
    path('clients/', views.client_list, name='clients'),
    path('products/', views.product_list, name='products'),
    path('orders/', views.orders_list, name='orders'),
    path('add_product/', views.add_product, name='add_product'),
    # path('__debug__/', include("debug_toolbar.urls")),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('create-order/', views.create_order, name='create_order'),
    path('order/<int:product_id>/', views.order_page, name='order_page'),
]

dz6app/models.py
from django.db import models


class Client(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.CharField(max_length=128)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    address = models.CharField(max_length=128)
    date_registered = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return (f'Id Client: {self.id}, Username: {self.client}, email: {self.email}, phone: {self.phone}, '
                f'address: {self.address}')


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='media/')
    def __str__(self):
        return f'Product #{self.id}: {self.product}, price: {self.price}, quantity: {self.quantity}'

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} x {self.product.product}'

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='OrderItem')
    date_ordered = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    def __str__(self):
        return f'Order {self.id} by {self.client.client}'
    def get_total_cost(self):
        return sum(item.quantity * item.product.price for item in self.orderitem_set.all())
    def update_total_price(self):
        self.total_price = self.get_total_cost()
        self.save()

dz6app/forms.py
from django import forms
from dz6app.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product', 'description', 'price', 'quantity', 'photo']

dz6app/views.py
from datetime import timezone, timedelta
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import redirect

from dz6app.forms import ProductForm
from .models import Product, Order, Client, OrderItem
from datetime import timedelta
from django.utils import timezone
from django.contrib import messages


# Create your views here.
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('save-success')  # Перенаправление после сохранения
    else:
        form = ProductForm()

    return render(request, 'add_product.html', {'form': form})


def view_name(request):
    return render(request, 'success.html')


def save_success(request):
    return render(request, 'success.html')


def unique_products_from_orders(orders):
    unique_products = set()
    for order in orders:
        for item in order.orderitem_set.all():
            unique_products.add(item.product)
    return unique_products


def client_orders(request, client_id):
    now = timezone.now()
    client_orders_last_7_days = Order.objects.filter(client_id=client_id, date_ordered__gte=now - timedelta(days=7))
    client_orders_last_month = Order.objects.filter(client_id=client_id, date_ordered__gte=now - timedelta(days=30))
    client_orders_last_year = Order.objects.filter(client_id=client_id, date_ordered__gte=now - timedelta(days=365))

    products_last_7_days = unique_products_from_orders(client_orders_last_7_days)
    products_last_month = unique_products_from_orders(client_orders_last_month)
    products_last_year = unique_products_from_orders(client_orders_last_year)

    context = {
        'products_last_7_days': products_last_7_days,
        'products_last_month': products_last_month,
        'products_last_year': products_last_year,
    }

    return render(request, 'client_products.html', context)


def my_page(request):
    return render(request, 'my_page.html')


def client_list(request):
    clients = Client.objects.all()
    return render(request, 'clients.html', {'clients': clients})


def product_list(request):
    sort = request.GET.get('sort', 'id')
    if sort == 'price':
        products = Product.objects.all().order_by('price')
    elif sort == 'name':
        products = Product.objects.all().order_by('product')
    else:
        products = Product.objects.all()
    return render(request, 'products.html', {'products': products})


def orders_list(request):
    orders = Order.objects.select_related('client').prefetch_related('products').all()
    return render(request, 'orders.html', {'orders': orders})


def total_in_template(request):
    context = {
        'title': 'Общее количество посчитано в шаблоне',
        'products': Product,
    }
    return render(request, 'total_count.html', context)


@require_http_methods(["POST"])
def subscribe(request):
    email = request.POST.get('email', '')
    return HttpResponse(f"Спасибо за подписку, ваш email: {email} получен!")


def create_order(request):
    if request.method == 'POST':
        # Получаем данные из формы
        client_name = request.POST.get('client')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        product_id = request.POST.get('product_id')

        client = Client(client=client_name, email=email, phone=phone, address=address)
        client.save()

        order = Order(client=client)
        order.save()

        product = Product.objects.get(id=product_id)
        order_item = OrderItem(product=product, order=order,
                               quantity=1)  # Предполагается, что заказывается 1 единица товара
        order_item.save()

        order.update_total_price()

        messages.success(request, 'Заказ успешно создан!'),
        return render(request, 'order_confirmation.html', {'product_id': product_id})

    return redirect('/')

def order_page(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'order_form.html', {'product': product})

templates/add_product.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Product</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Магазин №3{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Добавьте другие мета-теги, скрипты или CSS -->
    {% block extrahead %}{% endblock extrahead %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3p0R4nkn+45Jl9gOHdHkd0JCWR6sSO3eJJoCfs7s8x4pZdKEgvoLC5tHyJo" crossorigin="anonymous">
</head>
<body>
<header>
    <!-- Навигационная панель и другие элементы шапки -->
    <nav>
        <!-- Ссылки для навигации -->
    </nav>
</header>

<main>
    <!-- Основное содержимое страницы -->
    {% block content %}{% endblock content %}
</main>

<footer>
    <!-- Футер с информацией о копирайте и т.д. -->
    {% block footer %}
        <p>&copy; 2024 My Site</p>
    {% endblock footer %}
</footer>

<!-- Дополнительные скрипты -->
{% block extrajs %}{% endblock extrajs %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.9/dist/umd/popper.min.js" 
        integrity="sha384-eMNCOe7tC1doJ2ieThC7HH2kPHkfLdtWHA2Df3IgsorWl+WPoQWPmTOQHbT4vNf6" 
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" 
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+Wy4Ck4SOF4y4Ck4C2PhM+MO+1yRC+0+6r6" 
        crossorigin="anonymous"></script>
</body>
</html>

templates/client_products.html
{% extends "base.html" %}

{% block content %}
<h1>Заказанные товары</h1>

<div class="products-period">
    <h2>Товары за последние 7 дней</h2>
    <ul>
        {% for product in products_last_7_days %}
        <li>{{ product.product }} - {{ product.description }}</li>
        {% empty %}
        <li>Нет товаров за этот период.</li>
        {% endfor %}
    </ul>
</div>

<div class="products-period">
    <h2>Товары за последний месяц</h2>
    <ul>
        {% for product in products_last_month %}
        <li>{{ product.product }} - {{ product.description }}</li>
        {% empty %}
        <li>Нет товаров за этот период.</li>
        {% endfor %}
    </ul>
</div>

<div class="products-period">
    <h2>Товары за последний год</h2>
    <ul>
        {% for product in products_last_year %}
        <li>{{ product.product }} - {{ product.description }}</li>
        {% empty %}
        <li>Нет товаров за этот период.</li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

templates/clients.html
{% extends 'base.html' %}
{% block content %}
<h2>Список клиентов</h2>
<ul>
    {% for client in clients %}
    <li>{{ client.client }} - {{ client.email }} - +{{ client.phone }}</li>
    {% endfor %}
</ul>
{% endblock %}

templates/my_page.html
{% extends "base.html" %}

{% block content %}
<header class="main-header">
    <h1>Добро пожаловать в наш интернет-магазин!</h1>
    <p>Откройте для себя мир качественных товаров по отличным ценам каждый день.</p>
    <a href="{% url 'dz6app:products' %}" class="button-main">Изучить товары</a>
</header>

<section class="about-us">
    <h2>О нас</h2>
    <p>Мы предлагаем широкий ассортимент товаров для всех аспектов вашей жизни. Наша миссия — 
        обеспечить лучший выбор, качество и цену.</p>
</section>

<section class="newsletter-signup">
    <h2>Подпишитесь на наши новости</h2>
    <form action="{% url 'subscribe' %}" method="post">
        {% csrf_token %}
        <input type="email" placeholder="Ваш Email" required>
        <button type="submit" class="button-main">Подписаться</button>
    </form>
</section>

<footer class="main-footer">
    <p>© 2024 Интернет-магазин. Все права защищены.</p>
</footer>
{% endblock %}

templates/order_confirmation.html
{% extends 'base.html' %}

{% block content %}
    <h2>Заказ успешно создан!</h2>
    <p>Спасибо за ваш заказ. Мы скоро свяжемся с вами.</p>
    <a href="{% url 'dz6app:products' %}" class="button">Вернуться к товарам</a>
{% endblock %}

templates/order_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Форма заказа для {{ product.product }}</h2>

    <form method="post" action="{% url 'dz6app:create_order' %}">
        {% csrf_token %}
        <input type="hidden" name="product_id" value="{{ product.id }}">
        <div class="form-group">
            <label for="clientName">Имя:</label>
            <input type="text" class="form-control" id="clientName" name="client" required>
        </div>
        <div class="form-group">
            <label for="clientEmail">Email:</label>
            <input type="email" class="form-control" id="clientEmail" name="email" required>
        </div>
        <div class="form-group">
            <label for="clientPhone">Телефон:</label>
            <input type="text" class="form-control" id="clientPhone" name="phone" required>
        </div>
        <div class="form-group">
            <label for="clientAddress">Адрес:</label>
            <input type="text" class="form-control" id="clientAddress" name="address" required>
        </div>
        <button type="submit" class="btn btn-primary">Подтвердить заказ</button>
    </form>
{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% block content %}
<h2>Список заказов</h2>
<ul>
    {% for order in orders %}
    <li>Order ID: {{ order.id }} - Клиент: {{ order.client.client }} - Дата заказа: {{ order.date_ordered }} -
        Общая стоимость: ${{ order.total_price }}</li>
    {% endfor %}
</ul>
{% endblock %}

templates/products.html
{% extends 'base.html' %}

{% block content %}
    <h2>Список товаров</h2>

    <div class="sorting-buttons">
        <a href="?sort=name" class="button">Сортировать по имени</a>
        <a href="?sort=price" class="button">Сортировать по цене</a>
    </div>

    <div class="product-list">
        {% for product in products %}
            <div class="product-item">
                <h3 class="product-title">{{ product.product }}</h3>
                <p class="product-description">{{ product.description }}</p>
                <p class="product-price">${{ product.price }}</p>
                <a href="{% url 'dz6app:order_page' product.id %}" class="button">Заказать</a>    
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block content %}
<h2>Успех!</h2>
<p>Всё в порядке, продукт был успешно сохранён.</p>
{% endblock %}

templates/total_count.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <h3>{{ title }}</h3>
    {% if total %}
        <p>{{ total }}</p>
    {% endif %}
    {% if products %}
        <p>{{ products.total_quantity }}</p>
    {% endif %}
{% endblock %}